Create table STUDENTS
(
    SID VARCHAR2(5) primary key,
    NAME VARCHAR2(20),
    MARKS NUMBER
);

INSERT INTO STUDENTS VALUES('S001','Rahul',90);
INSERT INTO STUDENTS VALUES('S002','Tom',73);
INSERT INTO STUDENTS VALUES('S003','Anaya',35);
INSERT INTO STUDENTS VALUES('S004','Voldemort',42);
INSERT INTO STUDENTS VALUES('S005','Shaji',69);
INSERT INTO STUDENTS VALUES('S006','Tony',63);
